### ISSUE TITLE
"change" doesn't work with wicked_pdf Gem

### ISSUE THREAD

**Issue by tbraun89** [rails/turbolinks#495]
When I use the latest Turbolinks version together with [wicked_pdf](https://github.com/mileszs/wicked_pdf) the `change` functionality doesn't work but there is no error message. To reproduce the error you can just add the latest `wicked_pdf` Gem and use something like

    render :index, change: 'container'

the `#container` element will not be updated. I could track this error down to wicked_pdf's `alias_method_chain :render, :wicked_pdf` this part destroys the Turbolinks `change` functionality.

(Currently searching for a solution.)

**Comment by Thibaut** [comment]
It this still a problem with latest master?
We recently switched from using `alias_method_chain` to `prepend`.

**Comment by Thibaut** [comment]
This should be fixed now that we use `prepend` instead of `alias_method_chain`.

**Comment by daniel-rikowski** [comment]
I still have the same problem. 

Switching to `prepend` instead of `include` in `lib/turbolinks.rb` restores the functionality:

    if app.config.turbolinks.auto_include
       # include Controller # Doesn't work
       prepend Controller   # Works
    end

Setting `config.auto_include` to `false` and manually prepending `Turbolinks::Controller` in `ApplicationController` works, too.
